### ISSUE TITLE
Themes directory is empty

### ISSUE THREAD

**Issue by NazakatUmrani** [Nocxium/nChain#1]
I was checking your configs, in your readme it states that there should be folders inside themes directory, but I can't see any, there exists only one file .gitkeep.

**Comment by ecribia** [comment]
The theme folder is supposed to be empty when you clone my repo. The idea is that you should put your own themes there. The examples in the readme file is a showcase of the **structure** the folders should have once you have imported your own themes.

If you however are running a similar setup as me, and you like the themes that I have posted in the readme file, you can get the themes from here:
https://github.com/Nocxium/nChain-example

Just copy the contents from .config/nChain from that repo into your own nChain folder. You might have to tweak a few things in the script folder to match your setup :)
